# -*- coding: utf-8 -*-
"""Data_Vectorization_Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c7gkCe15CryA8mx61GOHkH9mEzAaj-gf
"""

#important necessary modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def vectorizeTextMatrix(textMatrix):
  """
  Input: combined text dataframe 
  This function vectorizes the text responses to each feature in the combined text matrix. Some variables are binary and represented by 0s and 1s. Some variables are ordinal and represented by an appropriate range of numbers.
  Output: vectorized dataframe
  """
  #Create a map of how we would like to vectorize data for each question 
  mappingQuestion1 = {'FALSE':0, 'TRUE':1}
  mappingQuestion2 = {'5-Jan':0, '25-Jun':1, '26-100':2, '100-500': 3, '500-1000': 4, 'More than 1000': 5}
  mappingQuestion3 = {'FALSE':0, 'TRUE':1}
  mappingQuestion5 = {'I don\'t know':-1, 'Not eligible for coverage / N/A':-1, 'Not eligible for coverage / NA':-1, 'No':0, 'Yes': 1}
  mappingQuestion6 = {'I am not sure':-1, 'NaN':-1, 'No':0, 'Yes': 1}
  mappingQuestion7 = {'I don\'t know':-1, 'No':0, 'Yes': 1}
  mappingQuestion8 = {'I don\'t know':-1, 'No':0, 'Yes': 1}
  mappingQuestion9 = {'I don\'t know':-1, 'No':0, 'Yes': 1}
  mappingQuestion10 = {'I don\'t know':-1, 'Very easy':0, 'Somewhat easy': 1, 'Neither easy nor difficult': 3, 'Somewhat difficult': 4, 'Difficult': 5, 'Very difficult': 6}
  mappingQuestion13 = {'No':0, 'Maybe': 1, 'Yes': 2}
  mappingQuestion14 = {'No':0, 'Maybe': 1, 'Yes': 2}
  mappingQuestion25 = {'FALSE':0, 'TRUE':1}
  mappingQuestion26 = {'No, none did': 0, 'Some did': 1, 'Yes, they all did': 2, 'I don\'t know': -1}
  mappingQuestion27 = {'N/A (none offered)': 0, 'N/A (was not aware)' :0, 'N/A (not currently aware)': 0, 'No, I only became aware later': 1, 'I was aware of some': 2, 'Yes, I was aware of all of them': 3}
  mappingQuestion28 = {'None did': 0, 'Some did': 1, 'Yes, they all did': 2, 'I don\'t know': -1}
  mappingQuestion29 = {'None did': 0, 'Some did': 1, 'Yes, they all did': 2, 'I don\'t know': -1}
  mappingQuestion30 = {'No': 0, 'Sometimes': 1, 'Yes, always': 2, 'I don\'t know': -1}
  mappingQuestion33 = {'No, at none of my previous employers': 0, 'At some of my previous employers': 1, 'Some of my previous employers': 1, 'Yes, at all of my previous employers': 2, 'I don\'t know': -1}
  mappingQuestion34 = {'No, at none of my previous employers': 0, 'No, none of my previous supervisors': 0, 'Some of my previous employers': 1, 'Some of my previous supervisors': 1, 'Yes, at all of my previous employers': 2, 'Yes, all of my previous supervisors':2,  'I don\'t know': -1}
  mappingQuestion40 = {'Not open at all': 0, 'Somewhat not open': 2, 'Neutral': 5, 'Somewhat open' : 8, 'Very open' : 10, 'Not applicable to me (I do not have a mental illness)': -1}
  mappingQuestion41 = {'No': 0, 'Maybe/Not sure': 1, 'Yes, I observed': 2, 'Yes, I experienced' : 3, 'I don\'t know': -1}
  mappingQuestion43 = {'No': 0, 'Yes': 1, 'I don\'t know': -1}
  mappingQuestion44 = {'No': 0, 'Maybe': 1, 'Possibly':2, 'Yes' :3, 'I don\'t know': -1, 'Don\'t Know': -1}
  mappingQuestion45 = {'No':0, 'Maybe':1, 'Possibly':1, 'Yes':2, 'Don\'t Know': -1}
  mappingQuestion50 = {'FALSE':0, 'TRUE':1}
  mappingQuestion51 = {'Never':0, 'Rarely':1, 'Sometimes':2, 'Often': 3, 'Not applicable to me': -1}
  mappingQuestion52 = {'Never':0, 'Rarely':1, 'Sometimes':2, 'Often': 3, 'Not applicable to me': -1}
  mappingQuestion53 = {}
  mappingQuestion54 = {'female':0, 'male':1, 'other':-1}
  mappingQuestion61 = {'No':0, 'Maybe':1, 'Yes':2}
  mappingQuestion62 = {'No':0, 'Maybe':1, 'Yes':2}

  #Create a map factorizing all the unique response options for question 55 "What country do you live in?"
  uniqueResponsesQuestion55 = textMatrix['55'].unique()
  mappingQuestion55 = {response: index for index, response in enumerate(uniqueResponsesQuestion55)}


  #Create a map factorizing all the unique response options for question 57 "What country do you work in?"
  uniqueResponsesQuestion57 = textMatrix['57'].unique()
  mappingQuestion57 = {response: index for index, response in enumerate(uniqueResponsesQuestion57)}

  listOfQuestionNumber = []
  for column in textMatrix.columns:
    listOfQuestionNumber.append(column)

  #replace all the data with the conditional maps we created
  for questionNumber in listOfQuestionNumber: 
    stringValue = "mappingQuestion" + str(questionNumber)
    textMatrix[questionNumber] = textMatrix[questionNumber].replace(globals()[stringValue])

  return textMatrix